### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by folliejester** [system32uwu/animu-desu#1]
{ error: 'read ECONNRESET' }

**Comment by wiredmatt** [comment]
Hello, thank you for posting your issue, can you provide further information on how are you getting this error so I can reproduce it? Post the code that you are using, and check that you are also using the latest version of animu-desu and nodejs.

In the worst case your requests might be getting blocked by cloudflare, which will only happen if you are not using proxies with your server, in my case I have a crontab job that changes the server IP every 1 minute as I'm expecting over 500 requests per minute.

If I had to guess, and if you were using express, you might have forgotten to use cors.

I have also developed an [app](https://github.com/system32uwu/sushi-night-backend) that uses this package with node and express, in case it helps you.

**Comment by folliejester** [comment]
i apologise for the disturbance i caused, its just that my retarded & oversmart govt. banned the anime sites to look cool and mature. i was able to access the contents using vpn/hosts. thank you for your dedication and hard work to make such useful things.

**Comment by wiredmatt** [comment]
No problem man, if you face anything else feel free to post it :).
